#include "../util/runner.h"
#include <iomanip>
#include <iostream>
#include <memory>
#include <vector>

using namespace std;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 two terms.
 * By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
*/
int even_fib()
{
  int sum = 2;
  int i_1 = 2;
  int i_2 = 1;
  int i = 3;
  while (sum < 4000000)
  {
    if (i % 2 == 0)
      sum += i;
    i = i_1 + i_2;
    i_2 = i_1;
    i_1 = i;
  }

  return sum;
}

int main()
{
  timer::Runner runner;
  runner.run(even_fib, 10);
  int ans = even_fib();
  cout << ans << endl;
  return 0;
}
